# Generated by Django 5.0.3 on 2024-04-23 21:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_reserva_nombre_de_usuario_alter_reserva_sala'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accesorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PRO', 'Proyector'), ('CAF', 'Cafetera'), ('AUR', 'Auriculares'), ('OTR', 'Otros')], default='PRO', max_length=3)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.sala')),
            ],
        ),
    ]
