# Generated by Django 5.0.3 on 2024-04-23 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_accesorio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesorio',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='accesorio',
            name='sala',
        ),
        migrations.RemoveField(
            model_name='accesorio',
            name='tipo',
        ),
        migrations.AddField(
            model_name='accesorio',
            name='nombre',
            field=models.CharField(default='Sin nombre', max_length=100),
        ),
        migrations.AddField(
            model_name='reserva',
            name='accesorios_reservados',
            field=models.ManyToManyField(blank=True, to='bookings.accesorio'),
        ),
    ]
