# Generated by Django 5.0.3 on 2024-04-24 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_rename_accesorios_reservados_reserva_accesorio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesorio',
            name='nombre',
            field=models.CharField(choices=[('Cafetera', 'Cafetera'), ('Proyector', 'Proyector'), ('Micrófono', 'Micrófono'), ('Pizarra', 'Pizarra')], default='Cafetera', max_length=20),
        ),
    ]
