# Generated by Django 5.0.3 on 2024-04-24 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_alter_accesorio_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesorio',
            name='nombre',
            field=models.CharField(choices=[('Caf', 'Cafetera'), ('Pro', 'Proyector'), ('Mic', 'Micrófono'), ('Piz', 'Pizarra')], default='Caf', max_length=3),
        ),
    ]
