# Generated by Django 5.0.3 on 2024-04-29 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_accesorio_nombre_usuario_alter_accesorio_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='accesorio',
        ),
        migrations.AlterField(
            model_name='accesorio',
            name='nombre',
            field=models.CharField(choices=[('Cafetera', 'Cafetera'), ('Proyector', 'Proyector'), ('Micrófono', 'Micrófono'), ('Pizarra', 'Pizarra')], default='Pizarra', max_length=15),
        ),
    ]
